# Generated by Django 2.2.9 on 2020-01-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carritocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
