# Generated by Django 2.2.9 on 2020-01-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20200125_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='identificador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='datos_payu',
            field=models.TextField(),
        ),
    ]
